### PR TITLE
ReportPage

### PR DESCRIPTION
**Pull request by puja335**
✅  ReportPage done

### CODE REVIEW

**Comment by aasiskrk** [comment]
Resolve conflicts

**Comment by puja335** [comment]
done

**Comment by aasiskrk** [comment]
there are still conflicts, look in the pubspec.lock file line 100 it has duplicate version, remove one and keep one

**Comment by puja335** [comment]
all conflict solved

**Review by shiX0 — APPROVED** [review]
done

**Review by aasiskrk — APPROVED** [review]
good job

**Pull request merged**
